### ISSUE TITLE
Scan and press fails with firmware v4.7

### ISSUE THREAD

**Issue by kyori19** [nicolas-kuechler/switchbot#13]
I recently bought a switchbot and tried to control with api and python.
But scanning and controlling the bot don't work.

Steps to reproduce

* Scan

  ```py
  from switchbot import Scanner
  s = Scanner()
  m = s.scan() # Push "Pair with Remote" in SwitchBot app
  ```

  Error:
  ```
  Can't init device hci0: Connection timed out (110)
  ERROR:pygatt.backends.gatttool.gatttool:Unexpected error when scanning: Invalid device: Network is down

  Traceback (most recent call last):
    File "/home/pi/.local/share/virtualenvs/switchbot-rpEz6xuZ/lib/python3.7/site-packages/pexpect/spawnbase.py", line 166, in read_nonblocking
      s = os.read(self.child_fd, size)
  OSError: [Errno 5] Input/output error
  ```

  I can get same error when I use flask api.

* Press button (Interactive Only)

  ```py
  b = Bot(mac = "xx:xx:xx:xx:xx:xx", id = 1, name = "Bedroom Light")
  b.press()
  ```

  Error:
  ```
  Can't init device hci0: Connection timed out (110)
  ERROR:pygatt.backends.gatttool.gatttool:Timed out connecting to CF:BF:8B:68:CB:8F after 5.0 seconds.
  ERROR:switchbot:pygatt: failed to connect to ble device
  Traceback (most recent call last):
    File "/home/pi/.local/share/virtualenvs/switchbot-rpEz6xuZ/lib/python3.7/site-packages/pygatt/backends/gatttool/gatttool.py", line 415, in connect
      self.sendline(cmd)
    File "/usr/lib/python3.7/contextlib.py", line 119, in __exit__
      next(self.gen)
    File "/home/pi/.local/share/virtualenvs/switchbot-rpEz6xuZ/lib/python3.7/site-packages/pygatt/backends/gatttool/gatttool.py", line 191, in event
      self.wait(event, timeout)
    File "/home/pi/.local/share/virtualenvs/switchbot-rpEz6xuZ/lib/python3.7/site-packages/pygatt/backends/gatttool/gatttool.py", line 157, in wait
        raise NotificationTimeout()
  pygatt.exceptions.NotificationTimeout: None
  ```

Environment

* SwitchBot Bot Firmware v4.7
* Raspberry Pi 3B+ Raspbian Buster Lite

**Comment by nicolas-kuechler** [comment]
@kyori19 
Hi, I don't have a bot with firmware 4.7 available but I don't think that this is the problem here.

It looks like the ble library that I use (pygatt) has problems to connect. 
This could be because some software packages are not up to date. 
I would recommend that you try the following:

- `sudo apt-get update` 
- `sudo apt-get upgrade`
- `sudo apt-get install build-essential libssl-dev libffi-dev python-dev`
- remove the `Pipefile.lock` file and reinstall the environement with `pipenv install` in the root directory of switchbot
- `sudo reboot` reboot your raspberry pi

btw. the scanning requires root privileges (but it would show you a different error).
Here there is a link which describes how to circumvent this:
https://www.raspberrypi.org/forums/viewtopic.php?t=151858

Let me know if this fixed your problem.

**Comment by kyori19** [comment]
@nicolas-kuechler Thanks for your comment.

Reinstall fixed all errors and now works fine.
Scan works without using mobile app.

> btw. the scanning requires root privileges (but it would show you a different error).

I fixed that issue by this command.

```
sudo setcap 'cap_net_raw,cap_net_admin+eip' `which hcitool`
```

**Comment by onsprng** [comment]
hi , i tried  to use usb bluetooth and disable onboard bluetooth to improve range but i got an error .

`Can't init device hci0: Connection timed out (110)
ERROR:pygatt.backends.gatttool.gatttool:Timed out connecting to FF:5E:AE:B1:5D:9D after 5.0 seconds.
ERROR:switchbot:pygatt: failed to connect to ble device
Traceback (most recent call last):
  File "/home/pi/.local/share/virtualenvs/pi-V9tpwFal/lib/python3.7/site-packages/pygatt/backends/gatttool/gatttool.py", line 415, in connect
    self.sendline(cmd)
  File "/usr/lib/python3.7/contextlib.py", line 119, in __exit__
    next(self.gen)
  File "/home/pi/.local/share/virtualenvs/pi-V9tpwFal/lib/python3.7/site-packages/pygatt/backends/gatttool/gatttool.py", line 191, in event
    self.wait(event, timeout)
  File "/home/pi/.local/share/virtualenvs/pi-V9tpwFal/lib/python3.7/site-packages/pygatt/backends/gatttool/gatttool.py", line 157, in wait
    raise NotificationTimeout()
pygatt.exceptions.NotificationTimeout: None

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/pi/.local/share/virtualenvs/pi-V9tpwFal/lib/python3.7/site-packages/switchbot.py", line 413, in _connect
    self.device = self.adapter.connect(self.mac, address_type=pygatt.BLEAddressType.random)
  File "/home/pi/.local/share/virtualenvs/pi-V9tpwFal/lib/python3.7/site-packages/pygatt/backends/gatttool/gatttool.py", line 421, in connect
    raise NotConnectedError(message)
pygatt.exceptions.NotConnectedError: Timed out connecting to FF:5E:AE:B1:5D:9D after 5.0 seconds.
^CTraceback (most recent call last):
  File "/home/pi/.local/share/virtualenvs/pi-V9tpwFal/lib/python3.7/site-packages/pygatt/backends/gatttool/gatttool.py", line 415, in connect
    self.sendline(cmd)
  File "/usr/lib/python3.7/contextlib.py", line 119, in __exit__
    next(self.gen)
  File "/home/pi/.local/share/virtualenvs/pi-V9tpwFal/lib/python3.7/site-packages/pygatt/backends/gatttool/gatttool.py", line 191, in event
    self.wait(event, timeout)
  File "/home/pi/.local/share/virtualenvs/pi-V9tpwFal/lib/python3.7/site-packages/pygatt/backends/gatttool/gatttool.py", line 157, in wait
    raise NotificationTimeout()
pygatt.exceptions.NotificationTimeout: None

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/pi/.local/share/virtualenvs/pi-V9tpwFal/lib/python3.7/site-packages/switchbot.py", line 413, in _connect
    self.device = self.adapter.connect(self.mac, address_type=pygatt.BLEAddressType.random)
  File "/home/pi/.local/share/virtualenvs/pi-V9tpwFal/lib/python3.7/site-packages/pygatt/backends/gatttool/gatttool.py", line 421, in connect
    raise NotConnectedError(message)
pygatt.exceptions.NotConnectedError: Timed out connecting to FF:5E:AE:B1:5D:9D after 5.0 seconds.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/pi/.local/share/virtualenvs/pi-V9tpwFal/lib/python3.7/site-packages/switchbot.py", line 235, in set_timers
    self._connect()
  File "/home/pi/.local/share/virtualenvs/pi-V9tpwFal/lib/python3.7/site-packages/switchbot.py", line 416, in _connect
    raise SwitchbotError(message="communication with ble device failed")
switchbotpy.switchbot_util.SwitchbotError: communication with ble device failed

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "hotwater.py", line 13, in <module>
    bot.set_mode(dual_state=True, inverse=False)
  File "/home/pi/.local/share/virtualenvs/pi-V9tpwFal/lib/python3.7/site-packages/switchbot.py", line 300, in set_mode
    self.set_timers(timers=[])
  File "/home/pi/.local/share/virtualenvs/pi-V9tpwFal/lib/python3.7/site-packages/switchbot.py", line 257, in set_timers
    self.adapter.stop()
  File "/home/pi/.local/share/virtualenvs/pi-V9tpwFal/lib/python3.7/site-packages/pygatt/backends/gatttool/gatttool.py", line 318, in stop
    time.sleep(0.1)
KeyboardInterrupt
 > Uploading "/home/pi/.local/share/virtualenvs/pi-V9tpwFal/lib/python3.7/site-packages/Button.txt" to "/Button/Button.txt"... ^C5
 > Downloading "/Button/Button.txt" to "/home/pi/.local/share/virtualenvs/pi-V9tpwFal/lib/python3.7/site-packages/Button.txt"... DONE
30
Can't init device hci0: Connection timed out (110)
ERROR:pygatt.backends.gatttool.gatttool:Timed out connecting to FF:5E:AE:B1:5D:9D after 5.0 seconds.
ERROR:switchbot:pygatt: failed to connect to ble device
Traceback (most recent call last):
  File "/home/pi/.local/share/virtualenvs/pi-V9tpwFal/lib/python3.7/site-packages/pygatt/backends/gatttool/gatttool.py", line 415, in connect
    self.sendline(cmd)
  File "/usr/lib/python3.7/contextlib.py", line 119, in __exit__
    next(self.gen)
  File "/home/pi/.local/share/virtualenvs/pi-V9tpwFal/lib/python3.7/site-packages/pygatt/backends/gatttool/gatttool.py", line 191, in event
    self.wait(event, timeout)
  File "/home/pi/.local/share/virtualenvs/pi-V9tpwFal/lib/python3.7/site-packages/pygatt/backends/gatttool/gatttool.py", line 157, in wait
    raise NotificationTimeout()
pygatt.exceptions.NotificationTimeout: None

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/pi/.local/share/virtualenvs/pi-V9tpwFal/lib/python3.7/site-packages/switchbot.py", line 413, in _connect
    self.device = self.adapter.connect(self.mac, address_type=pygatt.BLEAddressType.random)
  File "/home/pi/.local/share/virtualenvs/pi-V9tpwFal/lib/python3.7/site-packages/pygatt/backends/gatttool/gatttool.py", line 421, in connect
    raise NotConnectedError(message)
pygatt.exceptions.NotConnectedError: Timed out connecting to FF:5E:AE:B1:5D:9D after 5.0 seconds.
Traceback (most recent call last):
  File "/home/pi/.local/share/virtualenvs/pi-V9tpwFal/lib/python3.7/site-packages/pygatt/backends/gatttool/gatttool.py", line 415, in connect
    self.sendline(cmd)
  File "/usr/lib/python3.7/contextlib.py", line 119, in __exit__
    next(self.gen)
  File "/home/pi/.local/share/virtualenvs/pi-V9tpwFal/lib/python3.7/site-packages/pygatt/backends/gatttool/gatttool.py", line 191, in event
    self.wait(event, timeout)
  File "/home/pi/.local/share/virtualenvs/pi-V9tpwFal/lib/python3.7/site-packages/pygatt/backends/gatttool/gatttool.py", line 157, in wait
    raise NotificationTimeout()
pygatt.exceptions.NotificationTimeout: None

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/pi/.local/share/virtualenvs/pi-V9tpwFal/lib/python3.7/site-packages/switchbot.py", line 413, in _connect
    self.device = self.adapter.connect(self.mac, address_type=pygatt.BLEAddressType.random)
  File "/home/pi/.local/share/virtualenvs/pi-V9tpwFal/lib/python3.7/site-packages/pygatt/backends/gatttool/gatttool.py", line 421, in connect
    raise NotConnectedError(message)
pygatt.exceptions.NotConnectedError: Timed out connecting to FF:5E:AE:B1:5D:9D after 5.0 seconds.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "hotwater.py", line 13, in <module>
    bot.set_mode(dual_state=True, inverse=False)
  File "/home/pi/.local/share/virtualenvs/pi-V9tpwFal/lib/python3.7/site-packages/switchbot.py", line 300, in set_mode
    self.set_timers(timers=[])
  File "/home/pi/.local/share/virtualenvs/pi-V9tpwFal/lib/python3.7/site-packages/switchbot.py", line 235, in set_timers
    self._connect()
  File "/home/pi/.local/share/virtualenvs/pi-V9tpwFal/lib/python3.7/site-packages/switchbot.py", line 416, in _connect
    raise SwitchbotError(message="communication with ble device failed")
switchbotpy.switchbot_util.SwitchbotError: communication with ble device failed`
